export const FETCH_ARTICLE='FETCH_ARTICLE';
export const FETCH_ARTICLE_SUCCESS='FETCH_ARTICLE_SUCCESS';

//login
export const FETCH_LOGIN='FETCH_LOGIN';

//register
export const FETCH_REGISTER='FETCH_REGISTER';

//search
export const FETCH_SEARCH='FETCH_SEARCH';
export const FETCH_SEARCH_KEYWORD='FETCH_SEARCH_KEYWORD';

export const FETCH_DETAIL='FETCH_DETAIL';
export const FETCH_ADD_COMMENT='FETCH_ADD_COMMENT'


//CHAT
export const RECEIVE_MESSAGE='RECEIVE_MESSAGE';
export const SEND_MESSAGE='SEND_MESSAGE'

export const USER_MESSAGE = 'USER_MESSAGE';
export const SYSTEM_MESSAGE = 'SYSTEM_MESSAGE';
